[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyterpilot-ai"
version = "0.2.0"
description = "Agentic AI coding partner for IPython and Jupyter"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "ipython",
    "litellm"
]
authors = [
    {name = "Wajoud Noorani", email = "wajoudnoorani59@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: IPython",
    "Intended Audience :: Developers",
]

[project.optional-dependencies]
data = [
    "pandas",
    "sqlalchemy",
    "pymongo"
]

[project.urls]
"Homepage" = "https://github.com/wajoud/jupyterpilot-ai"
"Bug Tracker" = "https://github.com/wajoud/jupyterpilot-ai/issues"

[tool.setuptools.packages.find]
where = ["src"]
